version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.10
    - 8.0.17
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/react-table"
    versions:
    - 7.0.28
  - dependency-name: yup
    versions:
    - 0.32.8
  - dependency-name: "@date-io/dayjs"
    versions:
    - 2.10.6
